version: '3.8'
services:
  backend1:
    build: ./backend 
    restart: always 
    ports:
      - "4001:4000"
    env_file:
      - ./backend/.env 
    depends_on:
      - mongodb 
  
  backend2:
    build: ./backend 
    restart: always 
    ports:
      - "4002:4000"
    env_file:
      - ./backend/.env 
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:4-xenial 
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db 
  
  nginx:
    image: nginx:1-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      - backend1
      - backend2
      
volumes:
  mongodb_data: